name: riverpod_example
description: Example of Riverpod.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/analyzer
  analyzer: 7.6.0
  # https://pub.dev/packages/equatable
  equatable: 2.0.7
  # https://pub.dev/packages/flutter_hooks
  flutter_hooks: 0.21.3+1
  # https://pub.dev/packages/hooks_riverpod
  hooks_riverpod: 3.0.0
  # https://pub.dev/packages/http
  http: 1.5.0
  # https://pub.dev/packages/riverpod_annotation
  riverpod_annotation: 3.0.0

  flutter_riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: 2.7.0
  # https://pub.dev/packages/flutter_lints
  flutter_lints: 6.0.0
  # https://pub.dev/packages/riverpod_generator
  riverpod_generator: 3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true