name: signals_example
description: "Example of Signals."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/equatable
  equatable: 2.0.7
  # https://pub.dev/packages/get_it
  get_it: 8.0.3
  # https://pub.dev/packages/http
  http: 1.3.0
  # https://pub.dev/packages/signals
  signals: 6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: 5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true