name: get_example
description: Example of GetX.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/analyzer
  analyzer: 7.6.0
  # https://pub.dev/packages/equatable
  equatable: 2.0.7
  # https://pub.dev/packages/get
  get: 4.7.2
  # https://pub.dev/packages/http
  http: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: 6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true